//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Reflection;

[assembly: System.Reflection.AssemblyCompanyAttribute("Flawkee")]
[assembly: System.Reflection.AssemblyConfigurationAttribute("Debug")]
[assembly: System.Reflection.AssemblyFileVersionAttribute("1.2.0.0")]
[assembly: System.Reflection.AssemblyInformationalVersionAttribute("1.2.0.0+58d6a5037e5793db518f5b8c4f88d71581adaec9")]
[assembly: System.Reflection.AssemblyProductAttribute("Emby.Wizdom.Plugin")]
[assembly: System.Reflection.AssemblyTitleAttribute("Emby.Wizdom.Plugin")]
[assembly: System.Reflection.AssemblyVersionAttribute("1.2.0.0")]

// Generated by the MSBuild WriteCodeFragment class.

