//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Reflection;

[assembly: System.Reflection.AssemblyCompanyAttribute("Flawkee")]
[assembly: System.Reflection.AssemblyConfigurationAttribute("Release")]
[assembly: System.Reflection.AssemblyFileVersionAttribute("1.3.1.1")]
[assembly: System.Reflection.AssemblyInformationalVersionAttribute("1.3.1.1+ec7dae17cd2864cac8077c6de30e0c8a870504a7")]
[assembly: System.Reflection.AssemblyProductAttribute("Emby.Wizdom.Plugin")]
[assembly: System.Reflection.AssemblyTitleAttribute("Emby.Wizdom.Plugin")]
[assembly: System.Reflection.AssemblyVersionAttribute("1.3.1.1")]

// Generated by the MSBuild WriteCodeFragment class.

